name: Deploy

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: copy file to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWD }}
        port: ${{ secrets.PORT }}
        source: "mconfig-server"
        target: "~/mconfig-test"
    - name: copy file to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWD }}
        port: ${{ secrets.PORT }}
        source: "Makefile"
        target: "~/mconfig-test"
    - name: run app on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /mconfig-test
          make deploy
          echo "deploy success"
